In [2]:
#import Libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import tensorflow as tf

In [3]:
tf.__version__


'2.11.0'

In [5]:
#data Preprocessing
dataset=pd.read_csv('Churn_Modelling.csv')
X=dataset.iloc[:,3:-1].values
Y=dataset.iloc[:,-1].values

In [6]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [7]:
print(Y)

[1 0 1 ... 1 1 0]


In [8]:
#Gender
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [9]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [10]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder='passthrough')
X=np.array(ct.fit_transform(X))

In [11]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [12]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=0)

In [13]:
#feature Scalling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [14]:
ann = tf.keras.models.Sequential()

In [15]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [16]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [17]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [18]:
ann.fit(X_train, Y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 0.5300 - accuracy: 0.7915
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4589 - accuracy: 0.8048
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4260 - accuracy: 0.8181
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4042 - accuracy: 0.8280
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3876 - accuracy: 0.8385
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3742 - accuracy: 0.8446
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3649 - accuracy: 0.8497
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3583 - accuracy: 0.8540
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3542 - accuracy: 0.8545
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3512 - accura

250/250 [==============================] - 0s 1ms/step - loss: 0.3328 - accuracy: 0.8651
Epoch 82/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3331 - accuracy: 0.8635
Epoch 83/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3326 - accuracy: 0.8643
Epoch 84/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3328 - accuracy: 0.8649
Epoch 85/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3327 - accuracy: 0.8645
Epoch 86/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3326 - accuracy: 0.8648
Epoch 87/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3325 - accuracy: 0.8652
Epoch 88/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3327 - accuracy: 0.8646
Epoch 89/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3326 - accuracy: 0.8645
Epoch 90/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3325 - accuracy: 

In [19]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

1/1 [==============================] - 0s 91ms/step
[[False]]


In [20]:
Y_pred = ann.predict(X_test)
Y_pred = (Y_pred > 0.5)
print(np.concatenate((Y_pred.reshape(len(Y_pred),1), Y_test.reshape(len(Y_test),1)),1))

63/63 [==============================] - 0s 1ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [21]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test, Y_pred)
print(cm)
accuracy_score(Y_test, Y_pred)

[[1508   87]
 [ 194  211]]


0.8595

In [24]:
ann.save('churn.h5')